---
version: "3.7"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - 2181:2181
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=user
      - ZOO_SERVER_PASSWORDS=password
      - ZOO_CLIENT_USER=user
      - ZOO_CLIENT_PASSWORD=password
    networks:
      - NET-platform-queue-kafka
  kafka1:
    image: "bitnami/kafka:latest"
    depends_on:
      - zookeeper
    ports:
      - 19092:19092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_PORT=19092
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:19092
      - KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://host.docker.internal:19092
      - KAFKA_INTER_BROKER_USER=user
      - KAFKA_INTER_BROKER_PASSWORD=password
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=password
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    networks:
      - NET-platform-queue-kafka
  kafka2:
    image: "bitnami/kafka:latest"
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_PORT=29092
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:29092
      - KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://host.docker.internal:29092
      - KAFKA_INTER_BROKER_USER=user
      - KAFKA_INTER_BROKER_PASSWORD=password
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=password
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    networks:
      - NET-platform-queue-kafka
  kafka3:
    image: "bitnami/kafka:latest"
    depends_on:
      - zookeeper
    ports:
      - 39092:39092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_PORT=39092
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:39092
      - KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://host.docker.internal:39092
      - KAFKA_INTER_BROKER_USER=user
      - KAFKA_INTER_BROKER_PASSWORD=password
      - KAFKA_BROKER_USER=user
      - KAFKA_BROKER_PASSWORD=password
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    networks:
      - NET-platform-queue-kafka

networks:
  NET-platform-queue-kafka:
    driver: bridge
