---
version: "3.7"

services:
  redis-master:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    networks:
      - NET-platform-redis
  redis-slave1:
    image: bitnami/redis:latest
    depends_on:
      - redis-master
    ports:
      - 16379:16379
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password
      - REDIS_PASSWORD=password
    networks:
      - NET-platform-redis
  redis-slave2:
    image: bitnami/redis:latest
    depends_on:
      - redis-master
    ports:
      - 26379:26379
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password
      - REDIS_PASSWORD=password
    networks:
      - NET-platform-redis
  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    depends_on:
      - redis-master
    ports:
      - 6380:6380
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password
    networks:
      - NET-platform-redis

networks:
  NET-platform-redis:
    driver: bridge
